import Link from "next/link";
import {EmptyTeam} from "@/components/empty-team";
import {PageShell} from "@/components/page-shell";
import {StatisticsCustomizer,type Metric} from "@/components/statistics-customizer";
import {TeamSelector} from "@/components/team-selector";
import {db} from "@/lib/db";
import {pageContext} from "@/lib/page-data";
import {StatisticsService} from "@/services/statistics";
export const dynamic="force-dynamic";
const decimal=(value:number)=>value.toLocaleString("nl-NL",{minimumFractionDigits:1,maximumFractionDigits:1});
const percentage=(present:number,absent:number)=>present+absent?Math.round(present/(present+absent)*100):0;
type PlayerRow={id:string;name:string;matches:number;starts:number;goals:number;assists:number;saves:number;mvps:number;cards:number;matchAttendance:number;trainingAttendance:number};
// De bestaande bijdrage-per-duelmetriek blijft conceptueel player.perGame; de keuzelijst kan later met dezelfde sleutel worden uitgebreid.
function Ranking({title,teamId,players,value}:{title:string;teamId:string;players:PlayerRow[];value:(player:PlayerRow)=>number}){const rows=[...players].filter(player=>value(player)>0).sort((a,b)=>value(b)-value(a)).slice(0,10);return <section className="card ranking-card"><h2>{title}</h2>{rows.map((player,index)=><Link href={`/players/${player.id}?team=${teamId}`} className="ranking-row" key={player.id}><span>{index+1}</span><strong>{player.name}</strong><b>{value(player)}</b></Link>)}{!rows.length&&<p className="muted">Nog geen gegevens.</p>}</section>}
export default async function Statistics({searchParams}:{searchParams:Promise<{team?:string}>}){
 const query=await searchParams,{user,teams,team}=await pageContext(query.team);if(!team)return <PageShell user={user}><EmptyTeam/></PageShell>;
 const matchFilter={status:"finished" as const,OR:[{homeTeamId:team.id},{awayTeamId:team.id}]};
 const [matches,players,matchAttendance,trainingAttendance,preference]=await Promise.all([
  db.match.findMany({where:matchFilter,orderBy:{date:"asc"}}),
  db.player.findMany({where:{teamId:team.id},include:{matchStats:{where:{match:matchFilter}},events:{where:{match:matchFilter}},matchAttendance:true,trainingAttendance:true},orderBy:{displayName:"asc"}}),
  db.matchAttendance.groupBy({by:["status"],where:{player:{teamId:team.id}},_count:true}),
  db.trainingAttendance.groupBy({by:["status"],where:{player:{teamId:team.id}},_count:true}),
  db.statisticPreference.findUnique({where:{userId_teamId:{userId:user.id,teamId:team.id}}}),
 ]);
 const summary=StatisticsService.detailedSummary(matches,team.id),home=StatisticsService.summary(matches.filter(match=>match.homeTeamId===team.id),team.id),away=StatisticsService.summary(matches.filter(match=>match.awayTeamId===team.id),team.id);
 const count=(rows:typeof matchAttendance,status:"present"|"absent")=>rows.find(row=>row.status===status)?._count??0,matchPresent=count(matchAttendance,"present"),matchAbsent=count(matchAttendance,"absent"),trainingPresent=count(trainingAttendance,"present"),trainingAbsent=count(trainingAttendance,"absent");
 const playerRows:PlayerRow[]=players.map(player=>{const matches=player.matchStats.length,goals=player.matchStats.reduce((sum,stat)=>sum+stat.goals,0),assists=player.matchStats.reduce((sum,stat)=>sum+stat.assists,0),saves=player.matchStats.reduce((sum,stat)=>sum+stat.saves,0),mp=player.matchAttendance.filter(item=>item.status==="present").length,ma=player.matchAttendance.filter(item=>item.status==="absent").length,tp=player.trainingAttendance.filter(item=>item.status==="present").length,ta=player.trainingAttendance.filter(item=>item.status==="absent").length;return{id:player.id,name:player.displayName,matches,starts:player.matchStats.filter(stat=>stat.started).length,goals,assists,saves,mvps:player.matchStats.filter(stat=>stat.mvp).length,cards:player.events.filter(event=>["green_card","yellow_card","red_card"].includes(event.type)).length,matchAttendance:percentage(mp,ma),trainingAttendance:percentage(tp,ta)}});
 const totalSaves=playerRows.reduce((sum,player)=>sum+player.saves,0),metrics:Metric[]=[{key:"winPercentage",label:"Winstpercentage",value:`${summary.played?Math.round(summary.won/summary.played*100):0}%`,hint:`${summary.won} van ${summary.played}`},{key:"pointsPerGame",label:"Punten per duel",value:decimal(summary.pointsPerGame),hint:`${summary.points} totaal`},{key:"goalsForPerGame",label:"Goals voor / duel",value:decimal(summary.goalsForPerGame),hint:`${summary.goalsFor} totaal`},{key:"goalsAgainstPerGame",label:"Goals tegen / duel",value:decimal(summary.goalsAgainstPerGame),hint:`${summary.goalsAgainst} totaal`},{key:"cleanSheets",label:"Clean sheets",value:summary.cleanSheets,hint:`${summary.failedToScore}× niet gescoord`},{key:"unbeaten",label:"Langst ongeslagen",value:summary.longestUnbeaten,hint:`${summary.longestWinning} winst op rij`},{key:"matchAttendance",label:"Aanwezigheid wedstrijden",value:`${percentage(matchPresent,matchAbsent)}%`,hint:`${matchPresent} aanwezig · ${matchAbsent} afwezig`},{key:"trainingAttendance",label:"Aanwezigheid trainingen",value:`${percentage(trainingPresent,trainingAbsent)}%`,hint:`${trainingPresent} aanwezig · ${trainingAbsent} afwezig`},{key:"saves",label:"Keeperreddingen",value:totalSaves,hint:"Alle gespeelde wedstrijden"}];
 const records=matches.map(match=>{const result=StatisticsService.resultFor(match,team.id)!;return{result,margin:result.goalsFor-result.goalsAgainst}}),bestWin=records.filter(item=>item.margin>0).sort((a,b)=>b.margin-a.margin)[0],heaviestLoss=records.filter(item=>item.margin<0).sort((a,b)=>a.margin-b.margin)[0];
 return <PageShell user={user}><div className="page-head"><div><span className="eyebrow">Team- en spelersprestaties</span><h1>Statistieken</h1></div><TeamSelector teams={teams} current={team.id}/></div><StatisticsCustomizer teamId={team.id} metrics={metrics} initialKeys={preference?.metricKeys??[]}/><div className="performance-grid"><section className="card"><h2>Seizoensbalans</h2><p>{summary.won} winst · {summary.drawn} gelijk · {summary.lost} verlies</p><small className="muted">Grootste overwinning: {bestWin?`${bestWin.result.goalsFor}–${bestWin.result.goalsAgainst}`:"–"} · Zwaarste nederlaag: {heaviestLoss?`${heaviestLoss.result.goalsFor}–${heaviestLoss.result.goalsAgainst}`:"–"}</small></section><section className="card"><h2>Thuis en uit</h2><p>Thuis: {home.points} punten uit {home.played} · Uit: {away.points} punten uit {away.played}</p></section></div><section className="card player-statistics-card"><div className="card-head"><h2>Spelerstatistieken</h2><span className="badge">{playerRows.length} spelers</span></div><div className="table-scroll"><table className="statistics-table"><thead><tr><th>Speler</th><th>W</th><th>Basis</th><th>Goals</th><th>Assists</th><th>Reddingen</th><th>Wedstrijd aanwezig</th><th>Training aanwezig</th></tr></thead><tbody>{playerRows.map(player=><tr key={player.id}><td><Link href={`/players/${player.id}?team=${team.id}`}>{player.name}</Link></td><td>{player.matches}</td><td>{player.starts}</td><td>{player.goals}</td><td>{player.assists}</td><td>{player.saves||"–"}</td><td>{player.matchAttendance}%</td><td>{player.trainingAttendance}%</td></tr>)}</tbody></table></div></section><div className="ranking-grid"><Ranking title="Topscorers" teamId={team.id} players={playerRows} value={player=>player.goals}/><Ranking title="Meeste assists" teamId={team.id} players={playerRows} value={player=>player.assists}/><Ranking title="Meeste MVP's" teamId={team.id} players={playerRows} value={player=>player.mvps}/><Ranking title="Meeste kaarten" teamId={team.id} players={playerRows} value={player=>player.cards}/></div></PageShell>
}
