"use client";
import {useMemo,useState} from "react";
type Bump="patch"|"minor"|"major";
function nextVersion(current:string,bump:Bump){const [major,minor,patch]=current.split(".").map(Number);return bump==="major"?`${major+1}.0.0`:bump==="minor"?`${major}.${minor+1}.0`:`${major}.${minor}.${patch+1}`}
export function AppReleasePanel({latestVersion}:{latestVersion:string|null}){
  const [bump,setBump]=useState<Bump>("patch"),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),currentVersion=latestVersion??"1.1.0";
  const version=useMemo(()=>nextVersion(currentVersion,bump),[currentVersion,bump]),parts=version.split(".").map(Number),buildNumber=parts[0]*1_000_000+parts[1]*1_000+parts[2];
  async function publish(){if(!file)return;setBusy(true);setMessage("APK uploaden en controleren…");const response=await fetch("/api/admin/releases",{method:"POST",headers:{"content-type":"application/vnd.android.package-archive","x-stickstat-version":version,"x-stickstat-build-number":String(buildNumber)},body:file}),body=await response.json();setBusy(false);setMessage(response.ok?`Versie ${body.data.version} is gepubliceerd. Alle gebruikers hebben een notificatie gekregen.`:body.error?.message??"Publiceren mislukt")}
  return <section className="card" style={{marginTop:18}}><div className="card-head"><div><h2>App-update publiceren</h2><p className="muted">Bouw de APK lokaal en upload hem hier. De productieserver voert geen Android-build uit.</p></div><span className="badge accent">VEILIGE UPLOAD</span></div><div className="release-version-options">{(["patch","minor","major"] as const).map(value=><label key={value}><input type="radio" name="release-bump" checked={bump===value} onChange={()=>{setBump(value);setFile(null)}}/><strong>{value==="patch"?"Bugfix":value==="minor"?"Functie":"Grote versie"}</strong><span>{nextVersion(currentVersion,value)}</span></label>)}</div><div className="release-instructions"><span>Bouw lokaal exact deze versie:</span><code>.\scripts\build-apk.ps1 -Version {version} -BuildNumber {buildNumber}</code><small className="muted">Selecteer daarna <strong>mobile\dist\StickStat.apk</strong>.</small></div><label className="release-file"><span>APK-bestand voor versie {version}</span><input type="file" accept=".apk,application/vnd.android.package-archive" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><button className="button" disabled={busy||!file} onClick={()=>void publish()}>{busy?"Publiceren…":`Versie ${version} publiceren`}</button>{message&&<p className="muted" role="status" style={{marginTop:14}}>{message}</p>}</section>
}
