"use client";
import {Pencil,X} from "lucide-react";
import {useState} from "react";
import {useRouter} from "next/navigation";

type Participation="absent"|"substitute"|"starter";
type Row={playerId:string;name:string;participation:Participation;goals:number;greenCards:number;yellowCards:number;redCards:number;mvp:boolean;notes:string};

function Stepper({value,onChange,label,max=20}:{value:number;onChange:(value:number)=>void;label:string;max?:number}){return <div className="stepper" aria-label={label}><button type="button" onClick={()=>onChange(Math.max(0,value-1))}>−</button><strong>{value}</strong><button type="button" onClick={()=>onChange(Math.min(max,value+1))}>+</button></div>}
function CardDots({row}:{row:Row}){return <div className="card-dots">{Array.from({length:row.greenCards},(_,index)=><i className="green" key={`g${index}`}/>)}{Array.from({length:row.yellowCards},(_,index)=><i className="yellow" key={`y${index}`}/>)}{Array.from({length:row.redCards},(_,index)=><i className="red" key={`r${index}`}/>)}</div>}

export function MatchTeamStatsForm({matchId,teamId,teamScore,initialRows,canEdit}:{matchId:string;teamId:string;teamScore:number|null;initialRows:Row[];canEdit:boolean}){
  const router=useRouter(),[rows,setRows]=useState(initialRows),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const update=(index:number,change:Partial<Row>)=>setRows(current=>current.map((row,rowIndex)=>rowIndex===index?{...row,...change}:row)),playedRows=rows.filter(row=>row.participation!=="absent"),totalGoals=playedRows.reduce((total,row)=>total+row.goals,0);
  async function save(){setBusy(true);setMessage("");const payloadRows=rows.map(row=>({playerId:row.playerId,participation:row.participation,goals:row.goals,greenCards:row.greenCards,yellowCards:row.yellowCards,redCards:row.redCards,mvp:row.mvp,notes:row.notes})),response=await fetch(`/api/matches/${matchId}/team-stats`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({teamId,rows:payloadRows})}),body=await response.json();setBusy(false);if(!response.ok){setMessage(body.error?.message??"Opslaan mislukt");return}setMessage(body.data.unassignedGoals?`${body.data.unassignedGoals} goal(s) zijn nog niet aan een speler toegewezen.`:"Wedstrijdstatistieken opgeslagen.");setEditing(false);router.refresh()}

  if(!editing)return <section className="card" style={{marginTop:18,overflowX:"auto"}}><div className="card-head"><div><h2>Spelers & prestaties</h2><p className="muted" style={{margin:0}}>Geregistreerde gegevens van deze wedstrijd.</p></div><div className="member-actions"><span className="badge">{playedRows.length} meegedaan</span>{canEdit&&<button className="icon-button" type="button" title="Wedstrijdstatistieken aanpassen" aria-label="Wedstrijdstatistieken aanpassen" onClick={()=>{setMessage("");setEditing(true)}}><Pencil size={18}/></button>}</div></div><table><thead><tr><th>Speler</th><th>Rol wedstrijd</th><th>Goals</th><th>Kaarten</th><th>MVP</th><th>Notitie</th></tr></thead><tbody>{playedRows.map(row=><tr key={row.playerId}><td><strong>{row.name}</strong></td><td>{row.participation==="starter"?"Basis":"Wissel"}</td><td><strong>{row.goals}</strong></td><td><CardDots row={row}/></td><td>{row.mvp?"★":"–"}</td><td className="muted">{row.notes||"–"}</td></tr>)}</tbody></table>{!playedRows.length&&<div className="empty">Nog geen spelersstatistieken ingevoerd.</div>}{message&&<p className="muted" role="status" style={{marginTop:14}}>{message}</p>}</section>;

  return <section className="card match-entry"><div className="card-head"><div><h2>Wedstrijdstatistieken aanpassen</h2><p className="muted" style={{margin:0}}>Deelname, goals, kaarten, MVP en een korte notitie.</p></div><div className="member-actions"><span className={`badge ${teamScore!==null&&totalGoals===teamScore?"accent":""}`}>GOALS {totalGoals}/{teamScore??"?"}</span><button className="icon-button" type="button" title="Bewerken annuleren" aria-label="Bewerken annuleren" onClick={()=>{setRows(initialRows);setMessage("");setEditing(false)}}><X size={18}/></button></div></div><div className="match-entry-list">{rows.map((row,index)=><article className={row.participation==="absent"?"inactive":""} key={row.playerId}><div className="match-entry-player"><strong>{row.name}</strong><select className="input" value={row.participation} onChange={event=>update(index,{participation:event.target.value as Participation,goals:event.target.value==="absent"?0:row.goals,mvp:event.target.value==="absent"?false:row.mvp})}><option value="absent">Niet meegedaan</option><option value="substitute">Wissel</option><option value="starter">Basis</option></select></div><div><span>Goals</span><Stepper label={`Goals van ${row.name}`} value={row.goals} onChange={goals=>update(index,{goals})}/></div><div><span>Groen</span><Stepper max={3} label={`Groene kaarten van ${row.name}`} value={row.greenCards} onChange={greenCards=>update(index,{greenCards})}/></div><div><span>Geel</span><Stepper max={3} label={`Gele kaarten van ${row.name}`} value={row.yellowCards} onChange={yellowCards=>update(index,{yellowCards})}/></div><div><span>Rood</span><Stepper max={3} label={`Rode kaarten van ${row.name}`} value={row.redCards} onChange={redCards=>update(index,{redCards})}/></div><label className="mvp-check"><input type="radio" name="mvp" checked={row.mvp} disabled={row.participation==="absent"} onChange={()=>setRows(current=>current.map((item,rowIndex)=>({...item,mvp:rowIndex===index})))}/>MVP</label><input className="input notes" value={row.notes} maxLength={500} placeholder="Korte notitie (optioneel)" onChange={event=>update(index,{notes:event.target.value})}/></article>)}</div><div className="member-actions" style={{marginTop:18}}><button className="button" type="button" disabled={busy||Boolean(teamScore!==null&&totalGoals>teamScore)} onClick={()=>void save()}>{busy?"Opslaan…":"Wijzigingen opslaan"}</button><button className="button secondary" type="button" disabled={busy} onClick={()=>{setRows(initialRows);setMessage("");setEditing(false)}}>Annuleren</button>{teamScore!==null&&totalGoals<teamScore&&<span className="muted">Niet iedere goal hoeft aan een speler gekoppeld te worden.</span>}</div>{message&&<p className="muted" role="status" style={{marginTop:14}}>{message}</p>}</section>;
}
