"use client";
/* eslint-disable react-hooks/static-components */

import { Pencil, Trash2, X } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { MatchPhoto } from "@/components/match-photo";
import { MatchPhotoManager } from "@/components/match-photo-manager";

type Player = { id: string; name: string };
type EventType = "mvp" | "goal" | "save" | "green_card" | "yellow_card" | "red_card" | "custom";
type MatchEvent = { id: string; type: EventType; playerId: string | null; relatedPlayerId: string | null; notes: string | null; player: Player | null; relatedPlayer: Player | null };

const labels: Record<EventType, string> = { mvp: "Man of the Match", goal: "Goal", save: "Redding", green_card: "Groene kaart", yellow_card: "Gele kaart", red_card: "Rode kaart", custom: "Notitie" };
const cardTypes = new Set<EventType>(["green_card", "yellow_card", "red_card"]);

export function MatchTeamStatsForm({ matchId, teamId, initialEvents, players, teamPhotoPath, mvpPhotoPath, canEdit, canManagePhotos }: { matchId: string; teamId: string; initialEvents: Array<Omit<MatchEvent, "type"> & { type: string }>; players: Player[]; teamPhotoPath: string | null; mvpPhotoPath: string | null; canEdit: boolean; canManagePhotos: boolean }) {
  const router = useRouter();
  const [editing, setEditing] = useState<MatchEvent | null | "new">(null), [type, setType] = useState<EventType>("goal"), [playerId, setPlayerId] = useState(""), [relatedPlayerId, setRelatedPlayerId] = useState(""), [notes, setNotes] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const events = initialEvents.filter(event => event.type in labels) as MatchEvent[], mvp = events.filter(event => event.type === "mvp"), goals = events.filter(event => event.type === "goal"), saves = events.filter(event => event.type === "save"), cards = events.filter(event => cardTypes.has(event.type)), other = events.filter(event => event.type === "custom");
  function openNew() { setType("goal"); setPlayerId(""); setRelatedPlayerId(""); setNotes(""); setMessage(""); setEditing("new"); }
  function openEdit(event: MatchEvent) { setType(event.type); setPlayerId(event.playerId ?? ""); setRelatedPlayerId(event.relatedPlayerId ?? ""); setNotes(event.notes ?? ""); setMessage(""); setEditing(event); }
  async function save() {
    if (!playerId) { setMessage("Kies een speler."); return; }
    if (type === "custom" && !notes.trim()) { setMessage("Vul een notitie in."); return; }
    setBusy(true); setMessage(""); const data = { teamId, type, playerId: playerId || null, relatedPlayerId: type === "goal" ? relatedPlayerId || null : null, notes: notes.trim() || null };
    const response = await fetch(`/api/matches/${matchId}/events`, { method: editing === "new" ? "POST" : "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(editing === "new" ? data : { ...data, eventId: editing!.id }) }), body = await response.json(); setBusy(false);
    if (!response.ok) { setMessage(body.error?.message ?? "Opslaan mislukt"); return; } setEditing(null); router.refresh();
  }
  async function remove(event: MatchEvent) {
    if (!window.confirm(`${labels[event.type]} verwijderen?`)) return; setBusy(true); setMessage("");
    const response = await fetch(`/api/matches/${matchId}/events`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ teamId, eventId: event.id }) }), body = await response.json(); setBusy(false);
    if (!response.ok) { setMessage(body.error?.message ?? "Verwijderen mislukt"); return; } router.refresh();
  }
  function EventActions({ event }: { event: MatchEvent }) { return canEdit ? <div className="performance-event-actions"><button className="icon-button" type="button" aria-label={`${labels[event.type]} aanpassen`} onClick={() => openEdit(event)}><Pencil size={16} /></button><button className="icon-button danger" type="button" aria-label={`${labels[event.type]} verwijderen`} disabled={busy} onClick={() => void remove(event)}><Trash2 size={16} /></button></div> : null; }
  function EventCard({ event }: { event: MatchEvent }) { return <article className="performance-event"><div><strong>{labels[event.type]}</strong>{event.type === "goal" && <><span>Scoorder: {event.player?.name ?? "Onbekend"}</span>{event.relatedPlayer && <span>Assist: {event.relatedPlayer.name}</span>}</>}{event.type === "save" && <span>Keeper: {event.player?.name ?? "Onbekend"}</span>}{cardTypes.has(event.type) && <span>Speler: {event.player?.name ?? "Onbekend"}</span>}{event.type === "custom" && <>{event.player && <span>Speler: {event.player.name}</span>}<span>{event.notes}</span></>}{event.notes && event.type !== "custom" && <span>{event.notes}</span>}</div><EventActions event={event} /></article>; }
  function Section({ title, entries }: { title: string; entries: MatchEvent[] }) { return entries.length ? <section className="performance-section"><h3>{title}</h3>{entries.map(event => <EventCard key={event.id} event={event} />)}</section> : null; }
  const mvpName = mvp[0]?.player?.name ?? null;
  return <section className="card match-stats-view"><div className="card-head"><h2>Prestaties</h2>{canEdit && <button className="icon-button" type="button" aria-label="Prestatie toevoegen" onClick={openNew}><Pencil size={18} /></button>}</div>{events.length ? <div className="performance-list">{mvp.length > 0 && <section className="performance-section"><h3>Man of the Match</h3><article className="performance-event"><div><strong>{mvp[0].player?.name ?? "Onbekend"}</strong>{mvpPhotoPath && <MatchPhoto src={mvpPhotoPath} alt="Man of the Match" className="match-mvp-photo" />}</div><EventActions event={mvp[0]} /></article></section>}<Section title="Goals" entries={goals} /><Section title="Reddingen" entries={saves} /><Section title="Kaarten" entries={cards} /><Section title="Notities" entries={other} /></div> : <div className="empty stats-empty-state"><p>Nog geen prestaties ingevoerd.</p></div>}<MatchPhotoManager matchId={matchId} teamId={teamId} teamPhotoPath={teamPhotoPath} mvpPhotoPath={mvpPhotoPath} mvpName={mvpName} canEdit={canManagePhotos} />{message && <p className="error" role="alert">{message}</p>}{editing && <div className="lineup-dialog-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setEditing(null); }}><section className="card lineup-dialog" role="dialog" aria-modal="true" aria-labelledby="performance-dialog-title"><div className="card-head"><h3 id="performance-dialog-title">{editing === "new" ? "Prestatie toevoegen" : "Prestatie aanpassen"}</h3><button className="icon-button" type="button" aria-label="Sluiten" onClick={() => setEditing(null)}><X size={18} /></button></div><label>Gebeurtenis<select className="input" value={type} onChange={event => setType(event.target.value as EventType)}>{(Object.entries(labels) as [EventType, string][]).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>{type === "goal" ? "Scoorder" : "Speler"}<select className="input" value={playerId} onChange={event => setPlayerId(event.target.value)}><option value="">Kies een teamlid</option>{players.map(player => <option key={player.id} value={player.id}>{player.name}</option>)}</select></label>{type === "goal" && <label>Assist (optioneel)<select className="input" value={relatedPlayerId} onChange={event => setRelatedPlayerId(event.target.value)}><option value="">Geen assist</option>{players.filter(player => player.id !== playerId).map(player => <option key={player.id} value={player.id}>{player.name}</option>)}</select></label>}<label>Notitie {type === "custom" ? "" : "(optioneel)"}<textarea className="input" value={notes} maxLength={1000} onChange={event => setNotes(event.target.value)} /></label><button className="button" type="button" disabled={busy} onClick={() => void save()}>{busy ? "Bezig…" : editing === "new" ? "Toevoegen" : "Opslaan"}</button></section></div>}</section>;
}
