"use client";

import {useState} from "react";

type StandingRow={id:string;teamId:string;teamName:string;position:number;played:number;won:number;drawn:number;lost:number;goalsFor:number;goalsAgainst:number;goalDifference:number;points:number};
type Score={id:string;date:string;home:string;away:string;homeScore:number|null;awayScore:number|null};

function weekendLabel(value:string){const date=new Date(value),start=new Date(date);start.setDate(date.getDate()-((date.getDay()+6)%7));const end=new Date(start);end.setDate(start.getDate()+6);return `${start.toLocaleDateString("nl-NL",{day:"numeric",month:"short"})} – ${end.toLocaleDateString("nl-NL",{day:"numeric",month:"short"})}`}

export function StandingsView({competition,rows,currentTeamId,scores}:{competition:string;rows:StandingRow[];teams:{id:string;name:string;club:{name:string}}[];currentTeamId:string;scores:Score[]}){
  const [details,setDetails]=useState(false),[tab,setTab]=useState<"stand"|"scores">("stand");
  const scoreWeekends=scores.reduce<{label:string;scores:Score[]}[]>((groups,score)=>{const label=weekendLabel(score.date),group=groups.find(item=>item.label===label);if(group)group.scores.push(score);else groups.push({label,scores:[score]});return groups},[]);
  return <><div className="page-head page-head-with-tools"><div><span className="eyebrow">{competition}</span><h1>Stand</h1></div><div className="page-head-tools"><button className="detail-toggle" type="button" role="switch" aria-checked={details} onClick={()=>setDetails(value=>!value)}><span>Details</span><i aria-hidden="true"><b/></i></button></div></div><section className={`card standings-card ${details?"is-detailed":""}`}><nav className="match-tabs standings-tabs" aria-label="Standweergave"><button className={tab==="stand"?"active":""} onClick={()=>setTab("stand")}>Stand</button><button className={tab==="scores"?"active":""} onClick={()=>setTab("scores")}>Scores</button></nav>{tab==="stand"?<><table className="standings-table"><thead><tr><th>#</th><th>Team</th>{details&&<><th>GS</th><th>W</th><th>G</th><th>V</th><th>DV</th><th>DT</th></>}<th>DS</th><th>P</th></tr></thead><tbody>{rows.map(row=><tr className={row.teamId===currentTeamId?"active-row":""} key={row.id}><td><strong>{row.position}</strong></td><td className="team-name"><strong>{row.teamName}</strong></td>{details&&<><td>{row.played}</td><td>{row.won}</td><td>{row.drawn}</td><td>{row.lost}</td><td>{row.goalsFor}</td><td>{row.goalsAgainst}</td></>}<td className="goal-difference">{row.goalDifference>0?`+${row.goalDifference}`:row.goalDifference}</td><td className="points"><strong>{row.points}</strong></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">De stand verschijnt na de eerste succesvolle synchronisatie.</div>}</>:<div className="score-list">{scoreWeekends.map(group=><section className="score-weekend" key={group.label}><h3>{group.label}</h3>{group.scores.map(score=><article className="match-row" key={score.id}><div className="match-date">{new Date(score.date).toLocaleDateString("nl-NL",{day:"2-digit",month:"short"})}</div><div className="teams"><strong>{score.home}</strong><span className="match-versus">–</span><strong>{score.away}</strong></div><div className="score mono">{score.homeScore}–{score.awayScore}</div></article>)}</section>)}{!scores.length&&<div className="empty">Nog geen uitslagen beschikbaar.</div>}</div>}</section></>;
}
