"use client";
import {ChevronDown,ChevronUp,Settings2,X} from "lucide-react";import {useState} from "react";
export type Metric={key:string;label:string;value:string|number;hint:string};
const DEFAULT=["winPercentage","pointsPerGame","goalsForPerGame","goalsAgainstPerGame","matchAttendance","trainingAttendance"];
export function StatisticsCustomizer({teamId,metrics,initialKeys}:{teamId:string;metrics:Metric[];initialKeys:string[]}){
 const available=new Map(metrics.map(metric=>[metric.key,metric])),[keys,setKeys]=useState((initialKeys.length?initialKeys:DEFAULT).filter(key=>available.has(key))),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),hidden=metrics.filter(metric=>!keys.includes(metric.key));
 async function save(){setBusy(true);await fetch(`/api/teams/${teamId}/statistic-preferences`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({metricKeys:keys})});setBusy(false);setEditing(false)}
 function move(index:number,direction:number){setKeys(current=>{const next=[...current],target=index+direction;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target],next[index]];return next})}
 return <><div className="statistics-toolbar"><h2>Mijn basisstatistieken</h2><button className="button secondary" onClick={()=>setEditing(true)}><Settings2 size={16}/> Opties</button></div><section className="metrics statistics-metrics">{keys.map(key=>{const metric=available.get(key);return metric&&<div className="metric" key={key}><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.hint}</small></div>})}</section>{hidden.length>0&&<details className="card more-statistics"><summary>Meer statistieken ({hidden.length})</summary><section className="metrics">{hidden.map(metric=><div className="metric" key={metric.key}><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.hint}</small></div>)}</section></details>}{editing&&<div className="modal-backdrop"><section className="card statistics-modal" role="dialog" aria-modal="true"><div className="card-head"><div><h2>Basisstatistieken kiezen</h2><p className="muted">Vink aan en bepaal de volgorde.</p></div><button className="icon-button" onClick={()=>setEditing(false)} aria-label="Sluiten"><X/></button></div><div className="metric-order-list">{metrics.map(metric=>{const index=keys.indexOf(metric.key),checked=index>=0;return <div key={metric.key}><label><input type="checkbox" checked={checked} onChange={()=>setKeys(current=>checked?current.filter(key=>key!==metric.key):[...current,metric.key])}/>{metric.label}</label>{checked&&<span><button className="icon-button" disabled={index===0} onClick={()=>move(index,-1)}><ChevronUp size={16}/></button><button className="icon-button" disabled={index===keys.length-1} onClick={()=>move(index,1)}><ChevronDown size={16}/></button></span>}</div>})}</div><button className="button" disabled={busy||keys.length===0} onClick={()=>void save()}>{busy?"Opslaan…":"Voorkeur opslaan"}</button></section></div>}</>
}
