"use client";

import { Pencil, Trash2 } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ManagementDialog } from "@/components/player-management-controls";

type Role = "team_admin" | "coach" | "trainer" | "player" | "viewer";
type Player = { id: string; displayName: string; userId: string | null };
const roleOptions: [Role, string][] = [["player", "Speler"], ["coach", "Coach"], ["trainer", "Trainer"], ["team_admin", "Teambeheerder"], ["viewer", "Kijker"]];

async function request(url: string, method: string, data: Record<string, unknown>) { const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(data) }), body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Actie mislukt") }

export function TeamMemberManagement({ teamId, userId, roles, playerId, players, protectedAdmin }: { teamId: string; userId: string; roles: Role[]; playerId: string | null; players: Player[]; protectedAdmin: boolean }) {
  const router = useRouter(), [mode, setMode] = useState<"edit" | "remove" | null>(null), [selectedRoles, setSelectedRoles] = useState(roles), [selectedPlayerId, setSelectedPlayerId] = useState(playerId ?? ""), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  function close() { if (!busy) { setMode(null); setMessage(""); setSelectedRoles(roles); setSelectedPlayerId(playerId ?? "") } }
  function toggleRole(role: Role) { if (role === "team_admin" && protectedAdmin && selectedRoles.includes(role)) { setMessage("Dit is de enige teambeheerder. Wijs eerst iemand anders als teambeheerder aan."); return } setSelectedRoles(current => current.includes(role) ? current.filter(item => item !== role) : [...current, role]) }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const savedRoles = [...new Set<Role>([...selectedRoles, ...(protectedAdmin ? ["team_admin" as const] : []), ...(selectedPlayerId ? ["player" as const] : [])])]; try { await request(`/api/teams/${teamId}/members`, "POST", { userId, playerId: selectedPlayerId || null, roles: savedRoles }); setSelectedRoles(savedRoles); setMode(null); router.refresh() } catch (error) { setMessage(error instanceof Error ? error.message : "Teamlid bijwerken mislukt") } finally { setBusy(false) } }
  async function remove() { setBusy(true); setMessage(""); try { await request(`/api/teams/${teamId}/members`, "DELETE", { userId }); router.push(`/players?team=${teamId}`) } catch (error) { setMessage(error instanceof Error ? error.message : "Teamlid verwijderen mislukt"); setBusy(false) } }
  return <><div className="member-actions"><button className="icon-button" type="button" title="Rollen en koppeling bewerken" aria-label="Rollen en koppeling bewerken" onClick={() => setMode("edit")}><Pencil size={18} /></button><button className="icon-button danger-button" type="button" title="Account uit team verwijderen" aria-label="Account uit team verwijderen" onClick={() => setMode("remove")}><Trash2 size={18} /></button></div>{mode === "edit" && <ManagementDialog title="Rollen en spelerskoppeling" onClose={close}><form className="form-stack" onSubmit={save}><label>Spelersprofiel</label><select className="input" value={selectedPlayerId} onChange={event => setSelectedPlayerId(event.target.value)}><option value="">Niet aan een speler koppelen</option>{players.map(player => { const linkedElsewhere = Boolean(player.userId && player.userId !== userId); return <option value={player.id} disabled={linkedElsewhere} key={player.id}>{player.displayName}{linkedElsewhere ? " · gekoppeld aan ander account" : ""}</option> })}</select><fieldset><legend>Rollen</legend><div className="role-options">{roleOptions.map(([role, label]) => <label key={role}><input type="checkbox" checked={selectedRoles.includes(role)} onChange={() => toggleRole(role)} />{label}</label>)}</div></fieldset>{selectedPlayerId && <p className="muted">Bij een spelerskoppeling wordt de rol Speler automatisch toegevoegd.</p>}<div className="member-actions"><button className="button" disabled={busy}>{busy ? "Opslaan…" : "Wijzigingen opslaan"}</button><button className="button secondary" type="button" disabled={busy} onClick={close}>Annuleren</button></div>{message && <p className="form-message" role="alert">{message}</p>}</form></ManagementDialog>}{mode === "remove" && <ManagementDialog title="Account uit team verwijderen" onClose={close}><p>Dit verwijdert de teamtoegang en maakt een eventuele spelerskoppeling los. Het StickStat-account zelf blijft bestaan.</p><div className="member-actions"><button className="button danger-button" type="button" disabled={busy} onClick={() => void remove()}>{busy ? "Verwijderen…" : "Uit team verwijderen"}</button><button className="button secondary" type="button" disabled={busy} onClick={close}>Annuleren</button></div>{message && <p className="form-message" role="alert">{message}</p>}</ManagementDialog>}</>;
}
