"use client";

import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {ClubLogoEditor} from "@/components/club-logo-editor";
import {TeamInvitePanel} from "@/components/team-invite-panel";

type Role="team_admin"|"coach"|"trainer"|"player"|"viewer";
type Account={id:string;name:string;email:string;roles:Role[];playerId:string|null};
type Member={userId:string;name:string;email:string;roles:Role[]};
type Player={id:string;firstName:string;namePrefix:string|null;lastName:string;displayName:string;shirtNumber:number|null;position:string|null;userId:string|null;active:boolean};
type Club={id:string;name:string;logoPath:string|null};
type Invite={id:string;expiresAt:string;createdBy:string};
const roleOptions:[Role,string][]=[["player","Speler"],["coach","Coach"],["trainer","Trainer"],["team_admin","Teambeheerder"],["viewer","Kijker"]];
const labels=Object.fromEntries(roleOptions) as Record<Role,string>;

async function request(url:string,method:string,data:Record<string,unknown>){const response=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(data)}),body=await response.json();if(!response.ok)throw new Error(body.error?.message??"Actie mislukt")}
const matches=(value:string,query:string)=>value.toLocaleLowerCase("nl").includes(query.trim().toLocaleLowerCase("nl"));

export function TeamManagementPanel({teamId,club,canAdmin,accounts,members,players,invites,protectedAdminUserId}:{teamId:string;club:Club;canAdmin:boolean;accounts:Account[];members:Member[];players:Player[];invites:Invite[];protectedAdminUserId:string|null}){
  const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[accountSearch,setAccountSearch]=useState(""),[roleFilter,setRoleFilter]=useState<Role|"all">("all"),[playerSearch,setPlayerSearch]=useState(""),[editingPlayerId,setEditingPlayerId]=useState<string|null>(null);
  const [selectedUserId,setSelectedUserId]=useState(accounts[0]?.id??""),[selectedRoles,setSelectedRoles]=useState<Role[]>(accounts[0]?.roles??[]),[selectedPlayerId,setSelectedPlayerId]=useState(accounts[0]?.playerId??"");
  const activePlayers=useMemo(()=>players.filter(player=>player.active&&matches(player.displayName,playerSearch)),[players,playerSearch]),archivedPlayers=useMemo(()=>players.filter(player=>!player.active&&matches(player.displayName,playerSearch)),[players,playerSearch]);
  const filteredMembers=useMemo(()=>members.filter(member=>matches(`${member.name} ${member.email}`,accountSearch)&&(roleFilter==="all"||member.roles.includes(roleFilter))),[members,accountSearch,roleFilter]);
  const accountOptions=useMemo(()=>{const filtered=accounts.filter(account=>matches(`${account.name} ${account.email}`,accountSearch)&&(roleFilter==="all"||account.roles.includes(roleFilter))),selected=accounts.find(account=>account.id===selectedUserId);return selected&&!filtered.some(account=>account.id===selected.id)?[selected,...filtered]:filtered},[accounts,accountSearch,roleFilter,selectedUserId]);

  async function run(action:()=>Promise<void>,success:string){setBusy(true);setMessage("");try{await action();setMessage(success);setEditingPlayerId(null);router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Actie mislukt")}finally{setBusy(false)}}
  function toggleRole(role:Role){if(role==="team_admin"&&selectedUserId===protectedAdminUserId&&selectedRoles.includes(role)){setMessage("Dit is de enige teambeheerder. Wijs eerst een tweede teambeheerder aan voordat je deze rol verwijdert.");return}setSelectedRoles(current=>current.includes(role)?current.filter(item=>item!==role):[...current,role])}
  function selectAccount(userId:string){const account=accounts.find(item=>item.id===userId);setSelectedUserId(userId);setSelectedRoles(account?.roles??[]);setSelectedPlayerId(account?.playerId??"")}
  function playerPayload(form:FormData){return {firstName:String(form.get("firstName")),namePrefix:String(form.get("namePrefix"))||null,lastName:String(form.get("lastName")),shirtNumber:form.get("shirtNumber")?Number(form.get("shirtNumber")):null,position:String(form.get("position"))||null}}

  return <>
    <section className="card">
      <div className="card-head"><div><span className="eyebrow">Accounttoegang</span><h2>Account en rollen</h2></div><span className="badge">{members.length} GEKOPPELD</span></div>
      <div className="management-filters"><input className="input" type="search" value={accountSearch} onChange={event=>setAccountSearch(event.target.value)} placeholder="Zoek op naam of e-mail"/><select className="input" value={roleFilter} onChange={event=>setRoleFilter(event.target.value as Role|"all")}><option value="all">Alle rollen</option>{roleOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>
      <p className="muted">Kies een geregistreerd account. De huidige rollen worden direct aangevinkt; je kunt ze aanpassen en het account eventueel aan een speler koppelen.</p>
      <form className="binding-form" onSubmit={event=>{event.preventDefault();const roles=selectedUserId===protectedAdminUserId?[...new Set<Role>([...selectedRoles,"team_admin"])]:selectedRoles;void run(()=>request(`/api/teams/${teamId}/members`,"POST",{userId:selectedUserId,playerId:selectedPlayerId||null,roles}),"Account, rollen en spelerskoppeling opgeslagen.")}}>
        <label>Geregistreerd account<select className="input" value={selectedUserId} onChange={event=>selectAccount(event.target.value)} required>{accountOptions.map(account=><option value={account.id} key={account.id}>{account.name} ({account.email})</option>)}</select></label>
        <label>Spelersprofiel (optioneel)<select className="input" value={selectedPlayerId} onChange={event=>setSelectedPlayerId(event.target.value)}><option value="">Niet aan een speler koppelen</option>{players.filter(player=>player.active).map(player=><option value={player.id} key={player.id}>{player.displayName}{player.userId&&player.userId!==selectedUserId?" · gekoppeld aan ander account":""}</option>)}</select></label>
        <fieldset><legend>Rollen</legend><div className="role-options">{roleOptions.map(([value,label])=><label key={value}><input type="checkbox" checked={selectedRoles.includes(value)} onChange={()=>toggleRole(value)}/>{label}</label>)}</div></fieldset>
        <button className="button" disabled={busy||!selectedUserId}>Account en rollen opslaan</button>
      </form>
      {!selectedRoles.length&&<p className="muted admin-protection-note">Zonder aangevinkte rol blijft het account aan het team gekoppeld. Zolang er geen spelersprofiel is gekoppeld, staat het onderaan Teamleden.</p>}
      {selectedUserId===protectedAdminUserId&&<p className="muted admin-protection-note">Dit account is de enige teambeheerder. Die rol kan pas weg nadat je een tweede teambeheerder hebt aangewezen.</p>}
      {message&&<p className="form-message" role="status">{message}</p>}
    </section>

    <section className="card" style={{marginTop:18}}><div className="card-head"><h2>Huidige teamleden</h2><span className="badge">{filteredMembers.length} / {members.length}</span></div>{filteredMembers.length?filteredMembers.map(member=><div className="sync-item" key={member.userId}><div><strong>{member.name}</strong><div className="muted list-detail">{member.email}</div><div className="member-roles">{member.roles.length?member.roles.map(role=><span className="badge" key={role}>{labels[role]}</span>):<span className="badge">Geen rol</span>}</div></div><button className="button secondary" disabled={busy} onClick={()=>void run(()=>request(`/api/teams/${teamId}/members`,"DELETE",{userId:member.userId}),"Teamlid verwijderd.")}>Verwijderen</button></div>):<p className="muted">Geen teamleden gevonden met deze filters.</p>}</section>

    <section className="card" style={{marginTop:18}}>
      <div className="card-head"><div><span className="eyebrow">Selectiebeheer</span><h2>Spelersprofielen</h2></div><span className="badge">{activePlayers.length} ACTIEF</span></div>
      <input className="input management-search" type="search" value={playerSearch} onChange={event=>setPlayerSearch(event.target.value)} placeholder="Zoek speler op naam"/>
      {activePlayers.length?activePlayers.map(player=>editingPlayerId===player.id?<form className="player-edit-form" key={player.id} onSubmit={event=>{event.preventDefault();void run(()=>request(`/api/teams/${teamId}/players`,"PATCH",{playerId:player.id,...playerPayload(new FormData(event.currentTarget))}),"Speler bijgewerkt.")}}><div className="player-name-fields"><input className="input" name="firstName" defaultValue={player.firstName} required/><input className="input" name="namePrefix" defaultValue={player.namePrefix??""} placeholder="Tussenvoegsel"/><input className="input" name="lastName" defaultValue={player.lastName} required/></div><input className="input" name="shirtNumber" type="number" min="0" max="999" defaultValue={player.shirtNumber??""} placeholder="Rugnummer"/><input className="input" name="position" defaultValue={player.position??""} placeholder="Positie"/><div className="member-actions"><button className="button" disabled={busy}>Opslaan</button><button className="button secondary" type="button" onClick={()=>setEditingPlayerId(null)}>Annuleren</button></div></form>:<div className="sync-item" key={player.id}><div><strong>{player.displayName}</strong><div className="muted list-detail">{player.shirtNumber!=null?`#${player.shirtNumber}`:"Geen rugnummer"} · {player.position??"Geen positie"} · {player.userId?"account gekoppeld":"geen account gekoppeld"}</div></div>{canAdmin&&<div className="member-actions"><button className="button secondary" disabled={busy} onClick={()=>setEditingPlayerId(player.id)}>Bewerken</button><button className="button secondary danger-button" disabled={busy} onClick={()=>{if(window.confirm(`Weet je zeker dat je ${player.displayName} wilt archiveren? Oude wedstrijdstatistieken blijven bewaard.`))void run(()=>request(`/api/teams/${teamId}/players`,"DELETE",{playerId:player.id}),"Speler gearchiveerd.")}}>Archiveren</button></div>}</div>):<p className="muted">Geen actieve spelers gevonden.</p>}
      {archivedPlayers.length>0&&<details className="archived-players"><summary>Gearchiveerde spelers ({archivedPlayers.length})</summary>{archivedPlayers.map(player=><div className="sync-item" key={player.id}><div><strong>{player.displayName}</strong><div className="muted list-detail">Historische statistieken zijn bewaard</div></div>{canAdmin&&<button className="button secondary" disabled={busy} onClick={()=>void run(()=>request(`/api/teams/${teamId}/players`,"PATCH",{playerId:player.id,active:true}),"Speler hersteld.")}>Herstellen</button>}</div>)}</details>}
    </section>

    {canAdmin&&<><div className="profile-grid" style={{marginTop:18}}><section className="card"><h2>Speler toevoegen</h2><p className="muted">De naam op de spelerslijst wordt automatisch samengesteld.</p><form className="form-stack" onSubmit={event=>{event.preventDefault();void run(()=>request(`/api/teams/${teamId}/players`,"POST",{...playerPayload(new FormData(event.currentTarget)),active:true}),"Speler toegevoegd.")}}><div className="player-name-fields"><input className="input" name="firstName" aria-label="Voornaam" placeholder="Voornaam" required/><input className="input" name="namePrefix" aria-label="Tussenvoegsel" placeholder="Tussenvoegsel (optioneel)"/><input className="input" name="lastName" aria-label="Achternaam" placeholder="Achternaam" required/></div><input className="input" name="shirtNumber" type="number" min="0" max="999" placeholder="Rugnummer (optioneel)"/><input className="input" name="position" placeholder="Positie (optioneel)"/><button className="button" disabled={busy}>Speler toevoegen</button></form></section><ClubLogoEditor club={club}/></div><div style={{marginTop:18}}><TeamInvitePanel teamId={teamId} invites={invites}/></div></>}
  </>;
}
