"use client";

import {useState} from "react";
import {useRouter} from "next/navigation";
import {StyledDatePicker,StyledTimePicker} from "@/components/date-time-picker";
import {ManagementDialog} from "@/components/player-management-controls";

export function TrainingCreateForm({teamId}:{teamId:string}){
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),router=useRouter();
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget),response=await fetch(`/api/teams/${teamId}/trainings`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:form.get("title"),date:form.get("date"),startTime:form.get("startTime")||null,endTime:form.get("endTime")||null,venue:form.get("venue")||null,notes:form.get("notes")||null,repeatWeeks:Number(form.get("repeatWeeks"))})}),body=await response.json();setBusy(false);if(!response.ok)return setMessage(body.error?.message??"Toevoegen mislukt");setMessage(`${body.data.count} training(en) toegevoegd.`);setOpen(false);router.refresh()}
  return <><button className="button compact-button" type="button" onClick={()=>setOpen(true)}>Training +</button>{open&&<ManagementDialog title="Training toevoegen" onClose={()=>!busy&&setOpen(false)}><p className="muted">Maak één training of direct een wekelijkse reeks.</p><form className="form-stack" onSubmit={submit}><label>Titel<input className="input" name="title" defaultValue="Training" required maxLength={100}/></label><div className="training-fields"><StyledDatePicker name="date" label="Datum"/><StyledTimePicker name="startTime" label="Start"/><StyledTimePicker name="endTime" label="Einde"/><label>Wekelijks herhalen<select className="input" name="repeatWeeks" defaultValue="1"><option value="1">Niet herhalen</option><option value="4">4 weken</option><option value="8">8 weken</option><option value="12">12 weken</option><option value="26">26 weken</option><option value="52">52 weken</option></select></label></div><label>Locatie<input className="input" name="venue" maxLength={200}/></label><label>Notitie<textarea className="input" name="notes" maxLength={1000}/></label><div className="member-actions"><button className="button" disabled={busy}>{busy?"Toevoegen…":"Training(en) toevoegen"}</button><button className="button secondary" type="button" disabled={busy} onClick={()=>setOpen(false)}>Annuleren</button></div></form>{message&&<p className="muted" role="status">{message}</p>}</ManagementDialog>}</>;
}
