import { ProfilePhoto } from "@/components/profile-photo";
import { notFound } from "next/navigation";
import { PageShell } from "@/components/page-shell";
import { pageContext } from "@/lib/page-data";
import { db } from "@/lib/db";
import { StatsCharts } from "@/components/stats-charts";
import { PlayerDetailManagement } from "@/components/player-management-controls";
import { CheckCircle2 } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function PlayerDetail({ params, searchParams }: { params: Promise<{ playerId: string }>; searchParams: Promise<{ team?: string }> }) {
  const [{ playerId }, query] = await Promise.all([params, searchParams]), { user, teams } = await pageContext(query.team);
  const now = new Date();
  const player = await db.player.findUnique({ where: { id: playerId }, include: { user: true, team: { include: { club: true } }, matchStats: { where: { match: { status: "finished" } }, include: { match: true } }, events: { where: { match: { status: "finished" } } }, matchAttendance: true, trainingAttendance: { include: { training: true } } } });
  if (!player || !teams.some(team => team.id === player.teamId)) notFound();
  const teamMatchFilter={status:"finished" as const,OR:[{homeTeamId:player.teamId},{awayTeamId:player.teamId}]};
  const [teamPlayers,teamMatches]=await Promise.all([db.player.findMany({where:{teamId:player.teamId},include:{matchStats:{where:{match:teamMatchFilter}},events:{where:{match:teamMatchFilter}}}}),db.match.findMany({where:teamMatchFilter})]);
  const canAdmin = user.platformRole === "admin" || user.teamMemberships.some(membership => membership.teamId === player.teamId && membership.roles.includes("team_admin"));
  const played = player.matchStats.length, starts = player.matchStats.filter(stat => stat.started).length, goals = player.matchStats.reduce((total, stat) => total + stat.goals, 0), assists = player.matchStats.reduce((total, stat) => total + stat.assists, 0), saves = player.matchStats.reduce((total, stat) => total + stat.saves, 0), cards = player.events.filter(event => event.type.endsWith("_card")).length, mvps = player.matchStats.filter(stat => stat.mvp).length, photo = player.user?.photoPath ?? player.photoPath, matchesAttended = player.matchAttendance.filter(item => item.status === "present").length, matchesAbsent = player.matchAttendance.filter(item => item.status === "absent").length, trainingsAttended = player.trainingAttendance.filter(item => item.status === "present" && item.training.date < now).length, trainingsAbsent = player.trainingAttendance.filter(item => item.status === "absent" && item.training.date < now).length;
  const attendancePercentage = (present:number, absent:number) => present + absent ? Math.round(present / (present + absent) * 100) : 0;
  const leaderboardRank = (value:(teamPlayer:typeof teamPlayers[number])=>number) => { const own=teamPlayers.find(teamPlayer=>teamPlayer.id===player.id),ownValue=own?value(own):0;if(ownValue===0)return null;return 1+new Set(teamPlayers.map(value).filter(score=>score>ownValue)).size; };
  const leaderboardPositions=[
    {label:"Topscorers",rank:leaderboardRank(teamPlayer=>teamPlayer.matchStats.reduce((total,stat)=>total+stat.goals,0))},
    {label:"Assists",rank:leaderboardRank(teamPlayer=>teamPlayer.matchStats.reduce((total,stat)=>total+stat.assists,0))},
    {label:"MVP's",rank:leaderboardRank(teamPlayer=>teamPlayer.matchStats.filter(stat=>stat.mvp).length)},
    {label:"Kaarten",rank:leaderboardRank(teamPlayer=>teamPlayer.events.filter(event=>event.type.endsWith("_card")).length)},
  ].filter((position):position is {label:string;rank:number}=>position.rank!==null);
  const resultFor=(match:{homeTeamId:string;awayTeamId:string;homeScore:number|null;awayScore:number|null})=>{const ownHome=match.homeTeamId===player.teamId,goalsFor=ownHome?match.homeScore:match.awayScore,goalsAgainst=ownHome?match.awayScore:match.homeScore;return{goalsFor,goalsAgainst,won:goalsFor!==null&&goalsAgainst!==null&&goalsFor>goalsAgainst}};
  const playerResults=player.matchStats.map(stat=>resultFor(stat.match)),playerWins=playerResults.filter(result=>result.won).length,playerWinPercentage=played?Math.round(playerWins/played*100):0,teamResults=teamMatches.map(resultFor),teamWins=teamResults.filter(result=>result.won).length,teamWinPercentage=teamMatches.length?Math.round(teamWins/teamMatches.length*100):0;
  const playersWithMatches=teamPlayers.filter(teamPlayer=>teamPlayer.matchStats.length>0),teamAverage=(value:(teamPlayer:typeof teamPlayers[number])=>number)=>playersWithMatches.length?playersWithMatches.reduce((total,teamPlayer)=>total+value(teamPlayer),0)/playersWithMatches.length:0,teamGoalsPerGame=teamAverage(teamPlayer=>teamPlayer.matchStats.reduce((total,stat)=>total+stat.goals,0)/teamPlayer.matchStats.length),teamAssistsPerGame=teamAverage(teamPlayer=>teamPlayer.matchStats.reduce((total,stat)=>total+stat.assists,0)/teamPlayer.matchStats.length);
  const orderedStats=[...player.matchStats].sort((a,b)=>a.match.date.getTime()-b.match.date.getTime()),personalBest=Math.max(0,...orderedStats.map(stat=>stat.goals));let scoringRun=0,longestScoringRun=0;for(const stat of orderedStats){scoringRun=stat.goals>0?scoringRun+1:0;longestScoringRun=Math.max(longestScoringRun,scoringRun)}
  const mvpLeaders=teamPlayers.map(teamPlayer=>({name:teamPlayer.displayName,count:teamPlayer.matchStats.filter(stat=>stat.mvp).length})).filter(teamPlayer=>teamPlayer.count>0).sort((a,b)=>b.count-a.count),topMvpCount=mvpLeaders[0]?.count??0,topMvpNames=mvpLeaders.filter(teamPlayer=>teamPlayer.count===topMvpCount).map(teamPlayer=>teamPlayer.name),mvpMatches=[...player.matchStats].filter(stat=>stat.mvp).sort((a,b)=>b.match.date.getTime()-a.match.date.getTime());
  const chart = orderedStats.map(stat => ({ date: stat.match.date.toLocaleDateString("nl-NL", { day: "2-digit", month: "short" }), goalsFor: stat.goals, goalsAgainst: stat.assists, points: 0 }));
  const playerDetails = [player.shirtNumber !== null ? `#${player.shirtNumber}` : null, player.position, player.isSubstitute ? "Invalspeler" : null].filter(Boolean);
  const managementPlayer = { firstName: player.firstName, namePrefix: player.namePrefix, lastName: player.lastName, displayName: player.displayName, shirtNumber: player.shirtNumber, position: player.position, trainingMember: player.trainingMember, matchMember: player.matchMember, isSubstitute: player.isSubstitute, staffRoles: player.staffRoles.filter((role): role is "coach" | "trainer" => role === "coach" || role === "trainer") };
  return <PageShell user={user}>
    <div className="page-head player-detail-head"><div><span className="eyebrow">{player.team.club.name} · {player.team.name}</span><h1>{player.displayName}{player.userId && <span className="linked-player-status" tabIndex={0} data-tooltip="Speler heeft zijn account gekoppeld." aria-label="Speler heeft zijn account gekoppeld."><CheckCircle2 className="linked-player-check" size={21} /></span>}</h1>{playerDetails.length > 0 && <p className="muted">{playerDetails.join(" · ")}</p>}</div><div className="player-detail-actions">{photo ? <ProfilePhoto src={photo} name={player.displayName} size={80} /> : <div className="player-photo" style={{ width: 80, height: 80, fontSize: 25 }}>{player.firstName[0]}{player.lastName[0]}</div>}{canAdmin && <PlayerDetailManagement teamId={player.teamId} playerId={player.id} linkedAccount={Boolean(player.userId)} player={managementPlayer} />}</div></div>
    <section className="metrics player-detail-metrics" aria-label={`Statistieken van ${player.displayName}`}><div className="metric"><span>Wedstrijden</span><strong>{played}</strong><small>{starts}x in de basis</small></div><div className="metric"><span>Goals</span><strong>{goals}</strong><small>{played ? (goals / played).toFixed(1) : "0.0"} per wedstrijd</small></div><div className="metric"><span>Assists</span><strong>{assists}</strong><small>{played ? (assists / played).toFixed(1) : "0.0"} per wedstrijd</small></div><div className="metric"><span>G + A</span><strong>{goals + assists}</strong><small>Aanvallende bijdrage</small></div><div className="metric"><span>Reddingen</span><strong>{saves}</strong><small>In gespeelde wedstrijden</small></div><div className="metric"><span>Wedstrijd aanwezig</span><strong>{attendancePercentage(matchesAttended,matchesAbsent)}%</strong><small>{matchesAttended} aanwezig</small></div><div className="metric"><span>Training aanwezig</span><strong>{attendancePercentage(trainingsAttended,trainingsAbsent)}%</strong><small>{trainingsAttended} aanwezig</small></div><div className="metric"><span>MVP&apos;s</span><strong>{mvps}</strong><small>{cards} kaarten</small></div></section>
    {leaderboardPositions.length>0&&<section className="card player-leaderboard-positions"><div className="card-head"><div><span className="eyebrow">Teamranglijst</span><h2>Jouw posities</h2></div></div><div>{leaderboardPositions.map(position=><span className="player-leaderboard-position" key={position.label}><b>#{position.rank}</b>{position.label}</span>)}</div></section>}
    <div className="grid-2 player-insights"><section className="card"><span className="eyebrow">Wedstrijdimpact</span><h2>Winst met jou in het team</h2><p className="player-insight-value">{playerWinPercentage}%</p><p className="muted">{playerWins} winst uit {played} gespeelde wedstrijden. Het team staat dit seizoen op {teamWinPercentage}% winst.</p></section><section className="card"><span className="eyebrow">Teamvergelijking</span><h2>Per wedstrijd</h2><div className="player-comparison"><span>Goals <b>{played?(goals/played).toFixed(1):"0.0"}</b><small>teamgem. {teamGoalsPerGame.toFixed(1)}</small></span><span>Assists <b>{played?(assists/played).toFixed(1):"0.0"}</b><small>teamgem. {teamAssistsPerGame.toFixed(1)}</small></span></div></section></div>
    <section className="player-records"><div className="section-head"><div><span className="eyebrow">Persoonlijk</span><h2>Records</h2></div></div><div className="record-grid"><article className="record-card"><span>Meeste goals in een duel</span><strong>{personalBest}</strong><small>{personalBest?"Persoonlijk seizoensrecord":"Nog geen goals geregistreerd"}</small></article><article className="record-card"><span>Langste scorereeks</span><strong>{longestScoringRun} {longestScoringRun===1?"wedstrijd":"wedstrijden"}</strong><small>Achter elkaar gescoord</small></article><article className="record-card"><span>Huidige scorereeks</span><strong>{scoringRun} {scoringRun===1?"wedstrijd":"wedstrijden"}</strong><small>In de meest recente duels</small></article></div></section>
    <section className="card player-mvp-overview"><div className="card-head"><div><span className="eyebrow">Man of the Match</span><h2>MVP-overzicht</h2></div></div>{topMvpCount?<><p><strong>{topMvpNames.join(" & ")}</strong> {topMvpNames.length===1?"is":"zijn"} het vaakst MVP: {topMvpCount} {topMvpCount===1?"keer":"keer"}.</p>{mvpMatches.length>0&&<p className="muted">{player.displayName} was MVP op {mvpMatches.map(stat=>stat.match.date.toLocaleDateString("nl-NL",{day:"numeric",month:"short"})).join(", ")}.</p>}</>:<p className="muted">Er is nog geen MVP gekozen dit seizoen.</p>}</section>
    <StatsCharts matches={chart} players={[{ name: player.displayName, goals, assists }]} />
    <section className="card" style={{ marginTop: 18 }}><h2>Gemiddelden</h2><p className="muted">{played ? (goals / played).toFixed(2) : "0.00"} goals per wedstrijd · {played ? (assists / played).toFixed(2) : "0.00"} assists per wedstrijd</p></section>
  </PageShell>;
}
