import Link from "next/link";
import {AcceptTeamInvite} from "@/components/accept-team-invite";
import {RegisterForm} from "@/components/register-form";
import {currentUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {hashInviteToken,validInviteToken} from "@/lib/team-invites";

export const dynamic="force-dynamic";
export default async function JoinTeam({params}:{params:Promise<{token:string}>}){const {token}=await params,user=await currentUser(),invite=validInviteToken(token)?await db.teamInvite.findUnique({where:{tokenHash:hashInviteToken(token)},include:{team:{include:{club:true}}}}):null,available=invite&&!invite.usedAt&&invite.expiresAt>new Date();if(!available)return <main className="login-page"><section className="login-brand"><div className="brand"><span className="brand-mark">S</span>StickStat</div><div><span className="eyebrow" style={{color:"#c9f45b"}}>Teamuitnodiging</span><h1>Deze link is niet meer geldig.</h1><p>Vraag je teambeheerder om een nieuwe uitnodiging.</p></div></section><section className="login-panel"><div className="card login-form"><h2>Uitnodiging verlopen</h2><Link className="button invite-link-button" href={user?"/dashboard":"/login"}>{user?"Naar dashboard":"Log in"}</Link></div></section></main>;const teamName=`${invite.team.club.name} · ${invite.team.name}`;return <main className="login-page"><section className="login-brand"><div className="brand"><span className="brand-mark">S</span>StickStat</div><div><span className="eyebrow" style={{color:"#c9f45b"}}>Je bent uitgenodigd</span><h1>Welkom bij {invite.team.name}.</h1><p>{invite.team.club.name} gebruikt StickStat voor wedstrijden en teamstatistieken.</p></div></section><section className="login-panel">{user?<section className="card login-form"><span className="eyebrow">Teamuitnodiging</span><h2 style={{fontSize:32,marginTop:8}}>{teamName}</h2><AcceptTeamInvite token={token} teamName={teamName}/></section>:<RegisterForm inviteToken={token} teamName={teamName}/>}</section></main>}
